parameters:
   pim_research.infrastructure.delivery.http.graphql.class: Pim\Bundle\ResearchBundle\Infrastructure\Delivery\Http\GraphQLController

services:
   pim_research.infrastructure.delivery.http.graphql:
       class: '%pim_research.infrastructure.delivery.http.graphql.class%'
       arguments:
           - '@pim_research.infrastructure.delivery.api.graphql.type.query_type'
           - '@overblog_dataloader.webonyx_graphql_sync_promise_adapter'
